# Generated by Django 5.0.3 on 2024-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_rename_order_nate_order_order_note"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
