# Generated by Django 5.0.3 on 2024-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_orderproduct_color_remove_orderproduct_size"),
        ("store", "0005_alter_variation_variation_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
