# Generated by Django 5.0.3 on 2024-03-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_remove_orderproduct_variation_orderproduct_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier_company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
