# Generated by Django 5.0.3 on 2024-03-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_orderproduct_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="address_line_2",
            new_name="area",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="address_line_1",
            new_name="house_no",
        ),
        migrations.AddField(
            model_name="order",
            name="landmark",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
