# Generated by Django 5.0.4 on 2024-04-20 18:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_alter_order_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
