# Generated by Django 5.0.3 on 2024-03-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="pincode",
            field=models.CharField(max_length=50),
        ),
    ]
