# Generated by Django 5.0.3 on 2024-03-23 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_account_groups_account_is_superuser_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="account",
            name="user_permissions",
        ),
    ]
