# Generated by Django 5.0.3 on 2024-03-23 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_account_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="groups",
        ),
    ]
