# Generated by Django 5.0.3 on 2024-03-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_userprofile_landmark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
