# Generated by Django 5.0.3 on 2024-03-31 07:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0016_loggedindevices"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LoggedInDevices",
            new_name="LoggedInDevice",
        ),
    ]
