# Generated by Django 5.0.3 on 2024-04-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0018_delete_loggedindevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_two_factor",
            field=models.BooleanField(default=False),
        ),
    ]
