# Generated by Django 5.0.3 on 2024-03-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="video_thumbnail",
            field=models.ImageField(blank=True, upload_to="video/products"),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=models.FileField(blank=True, upload_to="video/products"),
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("size", "size"), ("color", "color")], max_length=100
            ),
        ),
    ]
