# Generated by Django 5.0.3 on 2024-03-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_alter_productgallery_options_specification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="seo_keyword",
        ),
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("size", "size"), ("color", "color")], max_length=100
            ),
        ),
        migrations.CreateModel(
            name="SeoKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seo_keyword", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="store.product"
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "unique_together": {("product",)},
            },
        ),
    ]
