# Generated by Django 5.0.3 on 2024-03-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_remove_product_seo_keyword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seokeyword",
            name="seo_keyword",
            field=models.CharField(blank=True),
        ),
    ]
