# Generated by Django 5.0.3 on 2024-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_alter_seokeyword_seo_keyword"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="seokeyword",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="seokeyword",
            name="seo_keyword",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="seokeyword",
            unique_together={("product", "seo_keyword")},
        ),
    ]
