# Generated by Django 5.0.3 on 2024-03-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0013_alter_seokeyword_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
    ]
