# Generated by Django 5.0.3 on 2024-04-07 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0035_alter_variation_variation_category_recentlyvisited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recentlyvisited",
            name="products",
        ),
        migrations.AlterField(
            model_name="recentlyvisited",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="recentlyvisited",
            name="products",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visited_by",
                to="store.product",
            ),
            preserve_default=False,
        ),
    ]
