# Generated by Django 5.0.3 on 2024-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0036_remove_recentlyvisited_products_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(
                choices=[("color", "color"), ("size", "size")], max_length=100
            ),
        ),
    ]
