# Generated by Django 5.0.4 on 2024-04-26 03:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0004_coupon_cart_applied_coupon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Coupon",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="applied_coupon",
        ),
    ]
